version: '3'
services:
  backend:
    image: node:14
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "${PORT}:${PORT}"
    command: >
      sh -c "
        npm install &&
        node server-normal.js
      "
    environment:
      - PORT=${PORT}
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
